export default {
	PROJECT_NAME: "Thoughts",

	MIN_PASSWORD_LENGTH: 6,
	MAX_PASSWORD_LENGTH: 30,

	MIN_ALLOWED_NAME_LENGTH: 1,
	MAX_ALLOWED_NAME_LENGTH: 20,
	MIN_ALLOWED_HANDLE_LENGTH: 1,
	MAX_ALLOWED_HANDLE_LENGTH: 15,

	VALID_NAME_CHARACTERS_EXPRESSION: /^[\p{L}\p{N}_\-\s!@#$%^&*()+=\[\]{}|\\;:'",.<>?\/`~]+$/u,
	VALID_HANDLE_CHARACTERS_EXPRESSION: /[A-Za-z0-9_]/,

	/** Milliseconds. */
	MAX_ALLOWED_SIGNUP_TOKEN_TIME: 60 * 1000,
	MAX_ALLOWED_POST_ATTACHMENT_SIZE: 50 * 1000 * 1000,
	MAX_ALLOWED_MESSAGE_ATTACHMENT_SIZE: 50 * 1000 * 1000,
	MAX_ALLOWED_POST_ATTACHMENTS: 4,
	MAX_ALLOWED_MESSAGE_ATTACHMENTS: 4,
	/** Bytes. */
	MAX_ALLOWED_AVATAR_SIZE: 10 * 1000 * 1000,

	/** Characters. */
	MIN_ALLOWED_POST_LENGTH: 1,
	MAX_ALLOWED_POST_LENGTH: 300,

	MAX_ALLOWED_MESSAGE_LENGTH: 1000,

	MAX_CONVERSATION_MESSAGES_PER_LOAD: 15,

	/** Milliseconds. */
	MAX_SESSION_TIME: 1000 * 60 * 60 * 24 * 30,

	MAX_POSTS_PER_LOAD: 10,
	MAX_MEDIA_ATTACHMENTS_PER_LOAD: 5,
	MAX_NOTIFICATIONS_PER_LOAD: 5,

	MAX_CONVERSATIONS_PER_LOAD: 10,

	MAX_SEARCH_SUGGESTIONS: 5,

	MAX_SEARCH_USER_RESULTS: 5,
	MAX_SEARCH_POST_RESULTS: 5,
	MAX_SEARCH_TAG_RESULTS: 5,
	MAX_REPLIES_PER_LOAD: 1,

	/** Milliseconds. */
	ACCOUNT_REMOVAL_GRACE_PERIOD: 5000,
}
